Local:                              # Environment name that can be passed on the command line
                                    #     (i.e.: ./goaws [Local | Dev]  -- defaults to 'Local')
  Host: localhost                   # hostname of the goaws system  (for docker-compose this is the tag name of the container)
  SQSPort: 9324                     # port SQS listens on.
  SNSPort: 9292                     # port SNS listens on.
  LogMessages: true                 # Log messages (true/false)
  LogFile: ./goaws_messages.log  # Log filename (for message logging
  Queues:                           # List of queues to create at startup
    - Name: local-queue1            # Queue name
    - Name: local-queue2            # Queue name
    - Name: local-queue3            # Queue name
  Topics:                           # List of topic to create at startup
    - Name: local-topic1            # Topic name - with some Subscriptions
      Subscriptions:                # List of Subscriptions to create for this topic (queues will be created as required)
        - QueueName: local-queue4   # Queue name
          Raw: false                # Raw message delivery (true/false)
        - QueueName: local-queue5   # Queue name
          Raw: true                 # Raw message delivery (true/false)
    - Name: local-topic2            # Topic name - no Subscriptions

NoQueuesOrTopics:                                # Another environment
  Host: localhost
  SQSPort: 9324
  SNSPort: 9292
  LogMessages: true
  LogFile: ./goaws_messages.log

